#!/usr/bin/env bash
STOW_FOLDERS="bin,zsh,nvim"
DOTFILES="$HOME/.dotfiles"

# Installing requirements
echo "Installing requirements..."

install_with_brew() {
    brew list $1 &>/dev/null || brew install $1
}

install_with_brew "stow"
install_with_brew "fzf"
install_with_brew "hugo"
install_with_brew "neovim"
install_with_brew "tmux"
install_with_brew "ripgrep"

# Setting permissions
echo "Setting permissions..."
chmod 755 ~/.local/scripts/*

echo "Setting up symlinks..."
pushd $DOTFILES &>/dev/null
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g"); do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd &>/dev/null
