#!/usr/bin/env bash
STOW_FOLDERS="bin,zsh,nvim,tmux,aerospace,ghostty"
DOTFILES="$HOME/.dotfiles"

echo "Setting up your Mac..."

# Check for Oh My Zsh and install if we don't have it
if test ! $(which omz); then
  /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/HEAD/tools/install.sh)"
fi

# Check for Homebrew and install if we don't have it
if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Setting permissions
echo "Setting permissions..."
chmod +x ~/.local/scripts/*
chmod +x ./sync-apps

echo "Setting up symlinks..."
pushd $DOTFILES &>/dev/null
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g"); do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd &>/dev/null

# Set my MacOS preferences
./sync-mac-settings
